version: '2'
services:
  proxy.local.arena.com.br:
    container_name: proxy.local.arena.com.br
    image: jwilder/nginx-proxy:latest
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro"
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      main:
        aliases:
          - proxy.local.arena.com.br

  stakearena-api.local.arena.com.br:
    container_name: stakearena-api.local.arena.com.br
    image: node:12.6.0-stretch
    working_dir: "/opt/app-root/src/"
    volumes:
      - "./api/:/opt/app-root/src/:rw"
    ports:
      - 80
    environment:
      VIRTUAL_HOST: 'stakearena-api.local.arena.com.br'
      DEV_MODE: 'true'
      SERVER_PORT: 80
    command: .s2i/bin/run
    networks:
      main:
        aliases:
          - stakearena-api.local.arena.com.br
  
networks:
  main: